services:
  influxdb:
    user: root
    image: influxdb:3-core
    container_name: influxdb3
    command: ["/bin/bash", "/entrypoint_influxdb.sh"]
    ports:
      - "8181:8181"
    volumes:
      - influxdb_data:/var/lib/influxdb3
      - ./entrypoint_influxdb.sh:/entrypoint_influxdb.sh
      - secrets:/secrets
    
  app:
    user: root
    build: .
    container_name: transform_influx
    env_file:
      - .env
    depends_on:
      - influxdb
    command: ["/bin/bash", "/entrypoint_app.sh"]
    volumes:
      - ./entrypoint_app.sh:/entrypoint_app.sh
      - secrets:/secrets
      
volumes:
  influxdb_data:
  secrets:
