services:
  influxdb:
    user: root
    image: influxdb:3.4.2-core
    container_name: influxdb
    command: ["/bin/bash", "/entrypoint_influxdb.sh"]
    ports:
      - "8181:8181"
    volumes:
      - influxdb_data:/var/lib/influxdb3
      - ./influxdb/entrypoint_influxdb.sh:/entrypoint_influxdb.sh
      - secrets:/secrets
  
  postgres:
    image: postgres:17.6-alpine3.22 
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - influxdb

  app:
    user: root
    # build: .
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/bin/bash", "/entrypoint_app.sh"]
    volumes:
      - ./app/entrypoint_app.sh:/entrypoint_app.sh
      - secrets:/secrets
      
volumes:
  influxdb_data:
  postgres_data:
    driver: local
  secrets:
