services:
  influxdb:
    user: root
    image: influxdb:3.4.2-core
    container_name: influxdb
    command: ["/bin/bash", "/entrypoint_influxdb.sh"]
    ports:
      - "8181:8181"
    volumes:
      - influxdb_data:/var/lib/influxdb3
      - ./influxdb/entrypoint_influxdb.sh:/entrypoint_influxdb.sh
      - secrets:/secrets
    
  app:
    user: root
    # build: .
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    depends_on:
      - influxdb
    command: ["/bin/bash", "/entrypoint_app.sh"]
    volumes:
      - ./app/entrypoint_app.sh:/entrypoint_app.sh
      - secrets:/secrets
      
volumes:
  influxdb_data:
  secrets:
