services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb_container
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_container
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket  # Pass the bucket name to the Python container

volumes:
  influxdb_data: