# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy files
# COPY . /app
COPY . . 

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt